version: "3.9"
services:
  mongo:
    image: mongo:jammy
    container_name: mongo
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - ${MONGO_VOLUME}:/data/db
  node:
    build: .
    restart: always
    ports:
      - ${PORT}:${PORT}
    # add logs volume
    volumes:
      - ./logs:/usr/src/app/logs
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
      DB_URL: ${DB_URL}
      DB_NAME: ${DB_NAME}
    depends_on:
      - mongo
