name: Deploy to Ubuntu Server

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH into Ubuntu Server and deploy
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        host: ${{ secrets.SSH_HOST }}
        script: |
          cd /root/cargo-backend
          git pull
          docker compose down
          docker compose up --build -d
          find /root/gurbet/cargo-backend -not -path '*/.git*' -delete
          cd /root/cargo-backend/
          find . \( -path './.git' -o -path './.github' \) -prune -o -print | cpio -pdm /root/gurbet/cargo-backend
          cd /root/gurbet/cargo-backend
          git add .
          git commit -m ${{ github.event.head_commit.message }}
          git push