name: Setup Node
on:
  push:
    branches: [ master ]

jobs:
  compose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: Build and start Docker Compose
      run: docker compose up -d
